[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/slack/oauth/callback"
  to = "/.netlify/functions/oauth-callback"
  status = 200 